export const WeatherIcons: {[key: number]: string} = {
    0: "day_clear.svg",
    1: "day_partial_cloud.svg",
    2: "cloudy.svg",
    3: "overcast.svg",
    45: "fog.svg",
    48: "mist.svg",
    51: "day_rain.svg",
    53: "day_rain.svg", 
    55:	"rain.svg",
    56: "day_sleet.svg", 
    57:	"sleet.svg",
    61: "rain.svg", 
    63: "rain.svg", 
    65:	"rain.svg",
    66: "day_sleet.svg", 
    67:	"sleet.svg",
    71: "day_snow.svg", 
    73: "day_snow.svg", 
    75: "snow.svg",
    77:	"Snow grains",
    80: "day_rain_thunder.svg", 
    81: "day_rain_thunder.svgs", 
    82: "rain_thunder.svg",
    85: "day_snow.svg", 
    86:	"snow_thunder.svg",
    95:	"thunder.svg",
    96: "snow_thunder.svg", 
    99:	"tornado.svg", 
}