export const WeatherIcons: {[key: number]: string} = {
    0: "assets/weather-icons/dovora/day_clear.svg",
    1: "assets/weather-icons/dovora/day_partial_cloud.svg",
    2: "assets/weather-icons/dovora/cloudy.svg",
    3: "assets/weather-icons/dovora/overcast.svg",
    45: "assets/weather-icons/dovora/fog.svg",
    48: "assets/weather-icons/dovora/mist.svg",
    51: "assets/weather-icons/dovora/day_rain.svg",
    53: "assets/weather-icons/dovora/day_rain.svg", 
    55:	"assets/weather-icons/dovora/rain.svg",
    56: "assets/weather-icons/dovora/day_sleet.svg", 
    57:	"assets/weather-icons/dovora/sleet.svg",
    61: "assets/weather-icons/dovora/rain.svg", 
    63: "assets/weather-icons/dovora/rain.svg", 
    65:	"assets/weather-icons/dovora/rain.svg",
    66: "assets/weather-icons/dovora/day_sleet.svg", 
    67:	"assets/weather-icons/dovora/sleet.svg",
    71: "assets/weather-icons/dovora/day_snow.svg", 
    73: "assets/weather-icons/dovora/day_snow.svg", 
    75: "assets/weather-icons/dovora/snow.svg",
    77:	"assets/weather-icons/dovora/Snow grains",
    80: "assets/weather-icons/dovora/day_rain_thunder.svg", 
    81: "assets/weather-icons/dovora/day_rain_thunder.svgs", 
    82: "assets/weather-icons/dovora/rain_thunder.svg",
    85: "assets/weather-icons/dovora/day_snow.svg", 
    86:	"assets/weather-icons/dovora/snow_thunder.svg",
    95:	"assets/weather-icons/dovora/thunder.svg",
    96: "assets/weather-icons/dovora/snow_thunder.svg", 
    99:	"assets/weather-icons/dovora/tornado.svg", 
}