export const weatherCodes: {[key: number]: string} =  {
    0: "Clear sky",
    1: "partly cloudy",
    2: "Mainly clear", 
    3: "cloudy and overcast", 
    45: "Fog", 
    48: "Depositing Rime Fog",
    51: "Light Drizzle intensity", 
    53: "Moderate Drizzle intensity", 
    55:	"Moderate dense intensity",
    56: "Light Freezing Drizzle Intensity", 
    57:	"Dense Freezing Drizzle Intensity",
    61: "Slight Rain intensity", 
    63: "moderate Rain intensity", 
    65:	"heavy Rain intensity",
    66: "Light Freezing Rain intensity", 
    67:	"heavy Freezing Rain intensity",
    71: "Slight Snow fall intensity", 
    73: "moderate Snow fall intensity", 
    75: "heavy Snow fall intensity",
    77:	"Snow grains",
    80: "Slight Rain showers", 
    81: "moderate Rain showers", 
    82: "violent Rain showers",
    85: "slight Snow showers", 
    86:	"heavy Snow showers",
    95:	"Slight or moderate Thunderstorm",
    96: "Thunderstorm with slight hail", 
    99:	"Thunderstorm with heavy hail",
};