export const weatherCodes: {[key: number]: string} =  {
    0: "Clear sky",
    1: "partly cloudy",
    2: "Mainly clear", 
    3: "cloudy and overcast", 
    45: "Fog", 
    48: "Rime Fog",
    51: "Light Drizzle", 
    53: "Moderate Drizzle", 
    55:	"Dense Drizzle",
    56: "Light Freezing Drizzle", 
    57:	"Dense Freezing Drizzle",
    61: "Slight Rain", 
    63: "moderate Rain", 
    65:	"heavy Rain",
    66: "Light Freezing Rain", 
    67:	"heavy Freezing Rain",
    71: "Slight Snow fall", 
    73: "moderate Snow fall", 
    75: "heavy Snow fall",
    77:	"Snow grains",
    80: "Slight Rain", 
    81: "moderate Rain", 
    82: "violent Rain",
    85: "slight Snow", 
    86:	"heavy Snow",
    95:	"Thunderstorm",
    96: "Thunderstorm with slight hail", 
    99:	"Thunderstorm with heavy hail",
};